# This file is machine-generated - editing it directly is not advised

julia_version = "1.10.2"
manifest_format = "2.0"
project_hash = "09236d1adac2c236fedffc219a24fdcbb4ada730"

[[deps.BioMarkovChains]]
deps = ["BioSequences", "PrecompileTools", "VectorizedKmers"]
git-tree-sha1 = "c48cc4efe18355a1a19ae627d05bf19df0a57253"
uuid = "f861b655-cb5f-42ce-b66a-341b542d4f2c"
version = "0.9.3"

    [deps.BioMarkovChains.extensions]
    DiscreteMarkovChainsExt = "DiscreteMarkovChains"
    MarkovChainHammerExt = "MarkovChainHammer"

    [deps.BioMarkovChains.weakdeps]
    DiscreteMarkovChains = "8abcb7ef-b365-4f7b-ac38-56893fb62f9f"
    MarkovChainHammer = "38c40fd0-bccb-4723-b30d-b2caea0ad8d9"

[[deps.BioSequences]]
deps = ["BioSymbols", "PrecompileTools", "Random", "Twiddle"]
git-tree-sha1 = "6fdba8b4279460fef5674e9aa2dac7ef5be361d5"
uuid = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
version = "3.1.6"

[[deps.BioSymbols]]
deps = ["PrecompileTools"]
git-tree-sha1 = "e32a61f028b823a172c75e26865637249bb30dff"
uuid = "3c28c6f8-a34d-59c4-9654-267d177fcfa9"
version = "5.1.3"

[[deps.Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[deps.IterTools]]
git-tree-sha1 = "42d5f897009e7ff2cf88db414a389e5ed1bdd023"
uuid = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
version = "1.10.0"

[[deps.PrecompileTools]]
deps = ["Preferences"]
git-tree-sha1 = "5aa36f7049a63a1528fe8f7c3f2113413ffd4e1f"
uuid = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
version = "1.2.1"

[[deps.Preferences]]
deps = ["TOML"]
git-tree-sha1 = "9306f6085165d270f7e3db02af26a400d580f5c6"
uuid = "21216c6a-2e73-6563-6e65-726566657250"
version = "1.4.3"

[[deps.Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[deps.Random]]
deps = ["SHA"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[deps.SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"
version = "0.7.0"

[[deps.StaticArraysCore]]
git-tree-sha1 = "36b3d696ce6366023a0ea192b4cd442268995a0d"
uuid = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"
version = "1.4.2"

[[deps.TOML]]
deps = ["Dates"]
uuid = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
version = "1.0.3"

[[deps.Twiddle]]
git-tree-sha1 = "29509c4862bfb5da9e76eb6937125ab93986270a"
uuid = "7200193e-83a8-5a55-b20d-5d36d44a0795"
version = "1.1.2"

[[deps.Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[deps.VectorizedKmers]]
deps = ["StaticArraysCore"]
git-tree-sha1 = "c2a7ec780efdf917088b5b65f78f402f72a2eb01"
uuid = "2ef45bd6-4c2b-43d8-88b3-40597287359a"
version = "0.9.2"
weakdeps = ["BioSequences"]

    [deps.VectorizedKmers.extensions]
    BioSequencesExt = "BioSequences"
